const data2 = [
    {
        key: 1,
        id: 1,
        name: "Egg",
        price: "60/Doz",
        sp: "50/Doz",
        cat: "dairy&deli",
        subcat: "poultry",
        img: "images/products/egg.jpeg",
        star: 5,
        color: "bg-yellow-400",
    },
    {
        key: 2,
        id: 2,
        name: "Milk-Buffalo",
        price: "50/Litre",
        sp: "40/Litre",
        cat: "dairy&deli",
        subcat: "dairy",
        img: "images/products/milk-2.jpeg",
        star: 4,
        color: "bg-blue-400",
    },
    {
        key: 3,
        id: 3,
        name: "Cheese",
        price: "300/Kg",
        sp: "250/Kg",
        cat: "dairy&deli",
        subcat: "dairy",
        img: "images/products/cheese.jpeg",
        star: 5,
        color: "bg-orange-400",
    },
    {
        key: 4,
        id: 4,
        name: "Pure-Honey",
        price: "400/Kg",
        sp: "350/Kg",
        cat: "dairy&deli",
        subcat: "other",
        img: "images/products/honey.jpeg",
        star: 4,
        color: "bg-amber-400",
    },
    {
        key: 5,
        id: 5,
        name: "Chicken",
        price: "200/Kg",
        sp: "180/Kg",
        cat: "dairy&deli",
        subcat: "meat",
        img: "images/products/chicken.jpeg",
        star: 5,
        color: "bg-pink-400",
    },
    {
        key: 6,
        id: 6,
        name: "Yogurt",
        price: "200/Kg",
        sp: "120/Kg",
        cat: "dairy&deli",
        subcat: "dairy",
        img: "images/products/yogurt.jpeg",
        star: 4,
        color: "bg-pink-400",
    }
];

export default data2;
