const data = [
  {
    key: 1,
    id: 1,
    name: "Banana",
    price: "40/Kg",
    sp: "30/kg",
    cat: "fruit&veg",
    subcat: "fruit",
    img: "images/products/banana.jpeg",
    star: 4,
    color: "bg-red-400",
  },{
    key: 2,
    id: 2,
    name: "Apple",
    price: "100/Kg",
    sp: "80/kg",
    cat: "fruit&veg",
    subcat: "fruit",
    img: "images/products/apple.jpeg",
    star: 4,
    color: "bg-red-400",
  },{
    key: 3,
    id: 3,
    name: "Alponsho-Mango",
    price: "100/Kg",
    sp: "60/kg",
    cat: "fruit&veg",
    subcat: "fruit",
    img: "images/products/mango-alphonso.jpeg",
    star: 5,
    color: "bg-red-400",
  },{
    key: 4,
    id: 4,
    name: "Cauliflower",
    price: "40/Kg",
    sp: "20/kg",
    cat: "fruit&veg",
    subcat: "veg",
    img: "images/products/cauliflower.jpeg",
    star: 4,
    color: "bg-red-400",
  },{
    key: 5,
    id: 5,
    name: "Tomato",
    price: "50/Kg",
    sp: "30/kg",
    cat: "fruit&veg",
    subcat: "veg",
    img: "images/products/tomato.jpeg",
    star: 3,
    color: "bg-red-400",
  },{
    key: 6,
    id: 6,
    name: "potatao",
    price: "30/Kg",
    sp: "20/kg",
    cat: "fruit&veg",
    subcat: "veg",
    img: "images/products/potato.jpeg",
    star: 4,
    color: "bg-red-400",
  }
];
export default data;
