const top=[
    {
        key:1,
        id:1,
        name:"Cow Milk",
        price:"100/ltr",
        sp:"60/ltr",
        cat:"dairy",
        subcat:"milk",
        img:"images/products/milk-3.jpeg",
        star:4,
        color:"bg-blue-400"
    },{
        key:2,
        id:2,
        name:"Wheat",
        price:"80/kg",
        sp:"50/kg",
        cat:"groceries",
        subcat:"cereals",
        img:"images/products/wheat.jpeg",
        star:5,
        color:"bg-yellow-500"
    },{
        key:3,
        id:3,
        name:"Almond",
        price:"200/kg",
        sp:"180/kg",
        cat:"groceries",
        subcat:"dryfruit",
        img:"images/products/almond.jpeg",
        star:4,
        color:"bg-red-400"
    },{
        key:4,
        id:3,
        name:"Badam",
        price:"200/kg",
        sp:"180/kg",
        cat:"groceries",
        subcat:"dryfruit",
        img:"images/products/almond.jpeg",
        star:4,
        color:"bg-yellow-500"
    },{
        key:5,
        id:3,
        name:"Badam",
        price:"200/kg",
        sp:"180/kg",
        cat:"groceries",
        subcat:"dryfruit",
        img:"images/products/almond.jpeg",
        star:4,
        color:"bg-yellow-500"
    },

];
export default top;